config/routes.rb
Rails.application.routes.draw do
  get 'todo_lists/index'
  get 'todo_items/index'
  get 'columns/index'
  get 'toppages/index'
  get 'images/index'
  get 'users/index'
  get 'training_records/index'

  devise_for :users
  root to:"toppages#index"

  resources :toppages, only: :index do
    collection do
      get 'privacy_policy'
      get 'regulation'
      get 'contact_us'
      get 'administrator_info'
    end
  end

  resources :columns do
  end

  resources :todo_lists do
    resources :todo_items
  end

  resources :users, only: [:index, :show] do
    member do      #id含む
      get 'records_update'
    end
    collection do  #id含まない
      get 'pagination'
    end
    resources :images, except: [:new, :show]
    resources :user_bodies, only: [:new, :create, :update]
    resources :training_records, only: [:index, :create, :destroy] do
      collection do
        get :draw_graph
      end
    end
  end

  resources :exercises, only: :index do
  end

  resources :relationships, only: [:create, :destroy] do
  end
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completo, -> do
    where(completo: true)
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET todo_lists/1/todo_items
  def index
    @todo_items = @todo_list.todo_items
  end

  # GET todo_lists/1/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.build
  end

  # POST todo_lists/1/todo_items
  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if @todo_item.save
      redirect_to(@todo_item.todo_list)
    else
      render action: 'new'
    end
  end

   # GET todo_lists/1/todo_items/1
   def show
   end

    # GET todo_lists/1/todo_items/1/edit
  def edit
  end

  # PUT todo_lists/1/todo_items/1
  def update
    if @todo_item.update_attributes(todo_item_params)
      redirect_to([@todo_item.todo_list, @todo_item], notice: '項目を更新しました')
    else
      render action: 'edit'
    end
  end

  # DELETE todo_lists/1/todo_items/1
  def destroy
    @todo_item.destroy

    
    respond_to do |format|
      format.html { redirect_to todo_lists_path(@todo_list), notice: "全項目削除しました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_item_params
      params.require(:todo_item).permit(:descricao, :completo, :completo_em, :todo_list_id)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_item.todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %>この項目の保存はできませんでした。:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :completo %><br />
    <%= f.check_box :completo %>
  </div>
  <div class="field">
    <%= f.label :completo_em %><br />
    <%= f.datetime_select :completo_em %>
  </div>
  <div class="field">
    <%= f.label :todo_list %><br />
    <%= f.text_field :todo_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>項目を編集する</h1>

<%= render 'form' %>

<%= link_to '詳細', [@todo_item.todo_list, @todo_item] %> |
<%= link_to '戻る', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_items/index.html.erb
<%= render "shared/header" %>

<h1>項目一覧</h1>

<table>
  <tr>
    <th>概要</th>
    <th>完了</th>
    <th>で完了</th>
    <th>To do list</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.descricao %></td>
    <td><%= todo_item.completo %></td>
    <td><%= todo_item.completo_em %></td>
    <td><%= todo_item.todo_list %></td>
    <td><%= link_to '表示', [todo_item.todo_list, todo_item] %></td>
    <td><%= link_to '編集', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item) %></td>
    <td><%= link_to '削除', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新しい目標の一覧', new_todo_list_todo_item_path(params[:todo_list_id]) %>

app/views/todo_items/new.html.erb
<h1>新しい目標</h1>

<%= render 'form' %>

<%= link_to '戻る', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>概要:</b>
  <%= @todo_item.descricao %>
</p>

<p>
  <b>完了:</b>
  <%= @todo_item.completo %>
</p>

<p>
  <b>完了する:</b>
  <%= @todo_item.completo_em %>
</p>

<p>
  <b>Todo list:</b>
  <%= @todo_item.todo_list %>
</p>


<%= link_to '編集する', edit_todo_list_todo_item_path(@todo_item.todo_list, @todo_item) %> |
<%= link_to '戻る', todo_list_todo_items_path(@todo_item.todo_list) %>