config/routes.rb
Rails.application.routes.draw do
  get 'todo_lists/index'
  get 'todo_items/index'
  get 'columns/index'
  get 'toppages/index'
  get 'images/index'
  get 'users/index'
  get 'training_records/index'

  devise_for :users
  root to:"toppages#index"

  resources :toppages, only: :index do
    collection do
      get 'privacy_policy'
      get 'regulation'
      get 'contact_us'
      get 'administrator_info'
    end
  end

  resources :columns do
  end

  resources :todo_lists do
    resources :todo_items
  end

  resources :users, only: [:index, :show] do
    member do      #id含む
      get 'records_update'
    end
    collection do  #id含まない
      get 'pagination'
    end
    resources :images, except: [:new, :show]
    resources :user_bodies, only: [:new, :create, :update]
    resources :training_records, only: [:index, :create, :destroy] do
      collection do
        get :draw_graph
      end
    end
  end

  resources :exercises, only: :index do
  end

  resources :relationships, only: [:create, :destroy] do
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_items, dependent: :destroy

  def percent_complete
    return 0 if total_items == 0
    (100 * completed_items.to_f / total_items).round(1)
  end


  def completed_items
    @completed_items ||= todo_items.completo.count
  end


  def total_items
    @total_items ||= todo_items.count
  end


  def status
    case percent_complete.to_i
    when 0
      'Não Iniciado'
    when 100
      'Completo'
    else
      'Em Progresso'
    end
  end

  def badge_color
    case percent_complete.to_i
    when 0
      'dark'
    when 100
      'success'
    else
      'primary'
    end
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only:[ :show, :edit, :update, :destroy ]

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_lists_path, notice: "作成されたすべての項目" }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

   # GET /todo_lists/1 or /todo_lists/1.json
  def show
    @todo_item = TodoItem.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_lists_path(@todo_list), notice: "更新しました" }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_path, notice: "項目が含まれていません" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:titulo)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> 項目の保存はできませんでした。</h2>
      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card-body">
    <div class="row">
      <div class="col-9">
        <div class="field">
          <%= form.text_field :titulo, class: 'form-control', placeholder: 'タイトル' %>
        </div>
      </div>
      <div class="col-2">
        <div class="actions">
        <div class="input-group-append">
          <%= form.submit "Salvar To Do", class: "btn btn-primary input-group-btn" %>
        </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="card-header d-flex justify-content-between">
  <h5 class="md-0 text-dark">
    編集する項目
  </h5>
  <%= link_to 'Voltar', @todo_list, class: "btn btn-dark" %> 
</div>

<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/index.html.erb
<div class="card-header d-flex justify-content-between">
  <h5 class="md-0 text-dark">
   Listagem To Do
  </h5>
  <%= link_to '新着順', new_todo_list_path, class: 'btn btn-primary btn-sm' %>
</div>
<div class="card-body ">
<div class="m-1">  
    <%= form_for :todo_list do |f| %>
      <div class="input-group mb-4">
        <%= f.text_field :titulo, class: 'form-control', placeholder: 'タイトル名一覧' %>
        <div class="input-group-append">
          <%= f.submit "保存する", class: "btn btn-primary input-group-btn" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row m-1">
    <% @todo_lists.order(:created_at).each do |todo_list| %>
      <div class="col-10" style='border:1px solid #f5f5f5; padding:20px 5px 20px 5px'>
        <%= link_to todo_list, class: "text-decoration-none" do %>      
          <h6 class='m-0 text-dark'>
            <b>
              <%= todo_list.titulo %>
            </b>
            <span class="badge badge-<%= todo_list.badge_color %>">
                <%= todo_list.status %>
            </span>
          </h6>
          <p class='text-secondary m-0'>
            <small>
              <%= todo_list.percent_complete %>% 完了 (<%= todo_list.completed_items %>/<%= todo_list.total_items %>) 全ての項目
            </small>
          </p>
        <% end %>
      </div>
      <div class="col-2" align="center"  style='border:1px solid #f5f5f5; padding:20px 1px 20px 1px'>
        <%= link_to "<button class='btn btn-danger'><i class='fa fa-trash'></i></button>".html_safe, { action: :destroy, id: todo_list.id }, method: :delete, data: { confirm: '本当に削除しますか？'} %>
      </div> 
    <% end %>
  </div>
</div>

app/views/todo_lists/new.html.erb
<div class="card-header d-flex justify-content-between">
  <h5 class="md-0 text-dark">
   やるべきこと
  </h5>
  <a href="<%= todo_lists_path %>" class="btn btn-dark">
    戻る
  </a>
</div>
<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/show.html.erb
<div class="card-header">
  <div class="row">
    <div class="col-1">
    <%= link_to todo_lists_path, class: "btn btn-dark" do %>
      <i class="fa fa-angle-left"></i>
    <% end %>
    </div>
      <div class="col-11">
        <div class="d-flex justify-content-between">
          <div>
            <h6 class='m-0'>
              <b><%= @todo_list.titulo %></b>
              <span class="badge badge-<%= @todo_list.badge_color %>"><%= @todo_list.status %></span>
            </h6>
            <p class='text-secondary m-0'><small><%= @todo_list.percent_complete %>% Completo (<%= @todo_list.completed_items %>/<%= @todo_list.total_items %>)全ての項目</small></p>
          </div>
          <div>
            <%= link_to '編集する', edit_todo_list_path(@todo_list), class: 'btn btn-secondary' %>
          </div>
          </div>  
        </div>
      </div>
  </div>
  <div class='card-body'>
    <div class="progress mb-4">
      <div class="progress-bar bg-success" role="progressbar" style="width:<%= @todo_list.percent_complete %>%" aria-valuenow="<%= @todo_list.percent_complete %>" aria-valuemin="0" aria-valuemax="100">
      </div>
    </div>
    <%= form_for([@todo_list, @todo_item]) do |f| %>
      <div class="input-group mb-4">
        <%= f.text_field :descricao, class: 'form-control', placeholder: '項目追加' %>
        <div class="input-group-append">
          <%= f.submit "追加する", class: "btn btn-primary input-group-btn" %>
        </div>
      </div>
    <% end %>
    <div class="row m-0">
      <% @todo_list.todo_items.order(:completo).each do |todo_item| %>
        <% if todo_item.completo? %>
          <div class=" col-12 p-2 border bg-light">
            <div class="row">
              <div class="col-9">
                <span class='text-secondary'>
                  <em><s>
                    <%= todo_item.descricao %>  
                  </em></s>
                </span>
              </div>
              <div class="col-3" align="right">          
               
                <%= link_to '#', class: 'btn btn-success', data: {reflex: "click->TodoItem#marcar_incompleto", id: todo_item.id } do %>
                <i class="fa fa-check"></i>
                 <% end %>

                <%= link_to "<button class='btn btn-danger'><i class='fa fa-trash'></i></button>".html_safe, [todo_item.todo_list, todo_item],method: :delete, data: { confirm: '本当に削除しますか？' } %>
              </div>
            </div>  
          </div>
        <% else %>
          <div class=" col-12 p-2 border bg-light">
            <div class="row">
              <div class="col-9">
                <span class='text-muted'>
                  <b>
                    <%= todo_item.descricao %>  
                  </b>
                </span>
              </div>
              <div class="col-3" align="right">          
                
              <%= link_to '#', class: 'btn btn-secondary', data: {reflex: "click->TodoItem#marcar_completo", id: todo_item.id } do %>
              <i class="fa fa-check"></i>
              <% end %>

                <%= link_to "<button class='btn btn-danger'><i class='fa fa-trash'></i></button>".html_safe, [todo_item.todo_list, todo_item],method: :delete, data: { confirm: '本当に削除しますか？' } %>
              </div>
            </div>  
          </div>
        <% end %>  
      <% end %>
    </div> 
  </div>
</div> 