config/routes.rb
Rails.application.routes.draw do
  get 'todo_lists/index'
  get 'todo_items/index'
  get 'columns/index'
  get 'toppages/index'
  get 'images/index'
  get 'users/index'
  get 'training_records/index'

  devise_for :users
  root to:"toppages#index"

  resources :toppages, only: :index do
    collection do
      get 'privacy_policy'
      get 'regulation'
      get 'contact_us'
      get 'administrator_info'
    end
  end

  resources :columns do
  end

  resources :todo_lists do
    resources :todo_items
  end

  resources :users, only: [:index, :show] do
    member do      #id含む
      get 'records_update'
    end
    collection do  #id含まない
      get 'pagination'
    end
    resources :images, except: [:new, :show]
    resources :user_bodies, only: [:new, :create, :update]
    resources :training_records, only: [:index, :create, :destroy] do
      collection do
        get :draw_graph
      end
    end
  end

  resources :exercises, only: :index do
  end

  resources :relationships, only: [:create, :destroy] do
  end
end

app/views/shared/_day_records_on_calendar.html.erb
<% parts = [] %>
<% training_records.each do |training_record| %>
  <% parts << training_record.part %>
<% end %>

app/views/shared/_delete_image.html.erb
<div class="card">
  <div class="form_group m-5 text-center">
    <h4>本当に削除しますか？</h4>
  </div>
  <div class="action mx-5 mb-5 row justify-content-around">
    <%= link_to '#', method: :delete, id: "delete-submit" do %>
      <i class="fas fa-3x fa-check-circle cursor_pointer d-inline-flex confirm_btn"></i>
    <% end %>
    <i class="fas fa-3x fa-times-circle close_button cursor_pointer d-inline-flex delete_btn" value="#delete_image"></i>
  </div>
</div>

app/views/shared/_edit_comment.html.erb
<%= form_with model: image, method: :patch, url: user_image_path(current_user.id,image), id: '', class: '', local: true do |image| %>
  <div class="form_group mx-5 mt-5 text-center">
    <h4>コメントの編集</h4>
  </div>
  <div class="form_group m-4">
    <%= image.text_area :comment, rows: 5, class: 'form_control w-100' %>
  </div>
  <div class="action m-5 row justify-content-around">
    <%= button_tag type: 'submit' , class: '' do %>
      <i class="fas fa-3x fa-check-circle cursor_pointer d-inline-flex confirm_btn"></i>
    <% end %>
    <i class="fas fa-3x fa-times-circle close_button cursor_pointer d-inline-flex cancel_btn" value="#html_to_modal_box"></i>
  </div>
<% end %>

app/views/shared/_follow_btn.html.erb
<% if @user.id == current_user.id %>
  <div class="btn btn-primary my-6 show_modal text-center" value="#edit_body">
    編集
  </div>
<% else %>
  <% if current_user.following?(user) %>
    <%= form_with model: current_user.relationships.find_by(follow_id: user.id), method: :delete do |f| %>
      <%= f.hidden_field :follow_id, value: user.id %>
      <%= f.submit "フォロー中", class: 'mt-3 follow_now_btn' %>
    <% end%>
  <% else %>
    <%= form_with model: current_user.relationships.build do |f| %>
      <%= f.hidden_field :follow_id, value: user.id %>
      <%= f.submit "フォローする", class: 'mt-3 follow_now_btn' %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to root_path do %>
      <%= link_to image_tag("will.icon.logo.png", class:"will-icon"), "/" %>
    <% end %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <% if user_signed_in? %> 
        <li><%= link_to 'ユーザー検索', users_path, class: "category-list" %></li>
        <li><%= link_to '写真', user_images_path(current_user.id), class: "category-list" %></li>
        <li><%= link_to '目標設定', todo_lists_path, class: "category-list" %></li>
        <li><%= link_to 'カレンダー', user_path(current_user.id), class: "category-list" %></li>
        <li><%= link_to '分析', user_training_records_path(current_user.id), class: "category-list" %></li>
        <li><%= link_to 'コラム', columns_index_path, class: "category-list" %></li>
      <% else %>
        <li><%= link_to 'コラム', columns_index_path, class: "category-list" %></li>
      <% end %>
    </ul>
    
    <ul class='lists-right'>
      <% if user_signed_in? %> 
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %> </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    </ul>
      <% end %>
  </div>
</header>

app/views/shared/_modal.html.erb
<div class="overlay"></div>
<div class="body_modal">
  <div class="body_modal__inner">
    編集ボタン
    <% unless @userbody == nil %>
      <div class="hide" id="edit_body">
        <%= render partial: "shared/user_body_edit" %>
      </div>
    <% end %>
    投稿削除ボタン
    <div class="hide" id="delete_image">
      <%= render partial: "shared/delete_image" %>
    </div>
    投稿コメント編集ボタン
    <div class="card hide" id="html_to_modal_box"></div>
    <% unless @follows == nil || @followers == nil %>
      フォロー表示ボタン
      <div class="hide" id="show_follows">
        <%= render partial: "shared/show_follows" %>
      </div>
      フォロー表示ボタン
      <div class="hide" id="show_followers">
        <%= render partial: "shared/show_followers" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_search_result.html.erb
<% unless @people.nil? %>
  <% @people.each do |people| %>
    <% unless [people.user_body.height,people.user_body.weight,people.user_body.experience].include?(nil) %>
      <%= link_to user_path(people.id) do %>
        <div class="user_searched">
          <div class="avatar_searched">
            <%= image_tag "#{people.user_body.avatar.url}" %>
          </div>
          <div class="user_detail_searched">
            <div class="name">#{people.nickname}
              <div class="body">#{people.user_body.height}cm/#{people.user_body.weight}kg</div>
                <div class="experience">
                  <%= "#{((Date.today.year - people.user_body.experience.year)*12 + Date.today.month - people.user_body.experience.month) / 12 + 1}年目" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <hr/>
      <% end %>
    <% end %>
  <% end %>
<% end%>
<%= link_to_next_page @people,'さらに表示', remote: true, class: 'btn btn-primary mb-3 block fontsize_12', id: 'search_next' %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>Will利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("show.edit.logo.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_show_followers.html.erb
<%# followers_result.card.background_color_light_black %>
  <div class="follow_title">
    <hr/>
    <p>フォロワー</p>
    <hr/>

    <div class="scroll background_color_white">
      <% @followers.each do |person| %>
        <%= link_to user_path(person.id), class: 'close_button' do %>
          <div class="user_searched">
            <div class="avatar_searched">
              <%= image_tag "#{person.user_body.avatar.url}" %>
            </div>
            <div class="user_detail_searched">
              <div class="name">#{person.nickname}
                <div class="body">#{person.user_body.height}cm/#{person.user_body.weight}kg</div>
                  <div class="experience">
                    <%= "#{((Date.today.year - person.user_body.experience.year)*12 + Date.today.month - person.user_body.experience.month) / 12 + 1}年目" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr/>
        <% end %>
      <% end %>
    </div>
    <div class="action m-5 row justify-content-around">
      <i class="fas fa-3x fa-times-circle close_button cursor_pointer d-inline-flex cancel_btn" value="#show_followers"></i>
    </div>
  </div>

app/views/shared/_training_records.html.erb
<li class="list-unstyled">
  <span class="remove_hidden_class">
    <i class="fas fa-plus"></i>
  </span>
  <span class="add_hidden_class hidden">
    <i class="fas fa-minus"></i>
  </span>
  <%= day_record.part %>
  <%= day_record.exercise %>
  <% if @user.id == current_user.id %>
    <span class="ml-2 record_delete_btn" value="<%= day_record.id %>">
      <i class="fas fa-times-circle cursor_pointer cancel_btn"></i>
    </span>
  <% end %>
  <ul class="hidden">
    <% day_record.menus.each do |menu| %>
      <% if day_record.part =="有酸素"%>
        <li class="menu-list">
          <%= menu.time %>
            分
          <% end %>
        </li>
      <% else %>
        <li class="menu-list">
          <%= menu.weight %>
            kg ×
          <% end %>
          <%= menu.rep %>
            will
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
</li>

app/views/shared/_user_body_edit.html.erb
<div class="card">
  <%= form_with model: @userbody, method: :patch, url: user_user_body_path(current_user.id,@userbody.id), id: 'new_userbody', class: 'new_userbody', local: true do |f| %>
    <div class="form_group m-4 edit_avatar">
      <%= f.label :avatar, class: 'avatar cursor_pointer mt-2'  do %>
        <%= image_tag "#{@userbody.avatar}", id: "avatar_image" %>
        <%= f.file_field :avatar, style: 'display :none;', class: 'form-control avatar_image_edit' %>
      <% end %>
      <p class="mt-2">
        <%= @user.nickname %>
      </p>
    </div>
  <% end %>
  <div class="form_group m-4">
    <%= f.label :birth_year, "誕生日" %>
    <%= f.number_field :birth_year, in: 1900...2019, class: 'form-control birth_year_number' %>
      <p class="edit_body_fail">1900以上2019以下で入力してください</p>
    <% end %>
  </div>
  <div class="form_group m-4">
    <%= f.label :gender,"性別" %>
    <%= f.select :gender, [['男性'], ['女']], prompt: '--', class: 'form-control' %>
  </div>
  <div class="form_group m-4">
    <%= f.label :height,'身長' %>
    <%= f.number_field :height, step: '0.1', in: 100...300, class: 'form-control height_number' %>
      <p class="edit_body_fail">100以上300以下で入力してください</p>
    <% end %>
  </div>
  <div class="form_group m-4">
  <%= f.label :weight,'体重' %>
  <%= f.number_field :weight, step: '0.1', in: 20...350, class: 'form-control weight_number' %>
    <p class="edit_body_fail">20以上350以下で入力してください</p>
  <% end %>
  <div class="form_group m-4">
    <%= f.label :experience,'筋トレ開始日' %>
    <br>
    <%= f.date_select :experience, start_year: 1960, end_year: Date.today.year, discard_day: true, class: 'form-control' %>
  </div>
  <div class="action m-5 row justify-content-around">
    <%= button_tag type: 'submit' , class: '' do %>
      <i class="fas fa-3x fa-check-circle cursor_pointer d-inline-flex confirm_btn"></i>
    <% end %>
    <i class="fas fa-3x fa-times-circle close_button cursor_pointer d-inline-flex cancel_btn" value="#edit_body"></i>
  </div>
</div>

app/views/shared/_user_images.html.erb
<% @images.each do |image| %>
  <div class="mx-3">
    <div class="head_box">
      <div class="photo_date">
        <%= image.created_at.strftime("%Y/%m/%d") %>
      </div>
      <div class="comment">
        <%= image.comment %>
      </div>
      <% if current_user.id == @user.id %>
        <div class="edit-btn ml-3">
          コメント編集ボタン
          <i class="fas fa-pencil-alt p-1 show_modal edit-comment" id="<%= image.id %>" value="#html_to_modal_box"></i>
        </div>
        <div class="ml-auto mb-2">
          記事削除ボタン
          <i class="fas fa-times-circle fa-2x cursor_pointer show_modal delete_btn" id="<%= image.id %>" value="#delete_image"></i>
        </div>
      <% end %>
    </div>
    <% image.user_image.each do |ele| %>
      <%= image_tag "#{ele}", class: 'photo-box' %>
    <% end %>
  </div>
  <hr/>
<% end %>
<%= link_to_next_page @images, 'さらに表示', remote: true, id: 'images_next', class: 'btn btn-primary mb-3 block fontsize_12' %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <%= render partial: "shared/follow_btn", locals: { user: @user } %>
  <%# <div class="avatar">
    <%= image_tag "#{@userbody.avatar}" %>
  <%# </div> %>
  <div class="nickname">
    <p>
      <%= user.nickname %>
    </p>
    <div class="follow_follower">
      <%# ここのvalueは表示するモーダルのid.モーダルの中でidが#show_follwsであるもののhideを取る。 %>
      <div class="show_modal follow inline-block cursor_pointer" value="#show_follows">
        <div class="follow__number">
          <%= "#{@user.follows.length}" %>
        </div>
      </div>
      <div class="follow__string">
        <%= 'フォロー' %>
      </div>
      <div class="show_modal follow inline-block ml-2 cursor_pointer" value="#show_followers">
        <div class="follow__number">
          <%= "#{@user.followers.length}" %>
        </div>
        <div class="follow__string">
          <%= "フォロワー" %>
        </div>
      </div>
    </div>
    <hr/>
    <ul class="row justify-content-around userinfo_link_list">
      <li>
        <%= link_to user_images_path(@user.id), class: 'text-blue mr-4' do %>
          <i class="fas fa-lg fas fa-camera"></i>
        <% end %>
      </li>
      <li>
        <%= link_to user_path(@user.id), class: 'text-blue mr-4' do %>
          <i class="far fa-lg fa-calendar-alt"></i>
        <% end %>
      </li>
      <li>
        <%= link_to user_training_records_path(@user.id), class: 'text-blue mr-4 chart_link_info' do %>
          <i class="fas fa-lg fa-chart-line"></i>
        <% end %>
      </li>
    </ul>
    <hr/>
  </div>

  <div class="body">
    <div class="height">
      <% if userbody&.height.nil? %>
        <p class="ml-2">
          <%= "--cm" %>
        </p>
      <% else %>
        <p class="ml-2">
          <%= "#{userbody&.height} cm" %>
        </p>
      <% end %>
    </div>
    <div class="weight ml-3">
      <% if userbody&.weight.nil? %>
        <p class="ml-2">
          <%= "--kg" %>
        </p>
      <% else %>
        <p class="ml-2">
          <%= "#{userbody&.weight} kg" %>
        </p>
      <% end %>
    </div>
    <div class="mt-1">
      <div class="userbody_title">BMI</div>
        <% if userbody&.height.nil? || userbody&.weight.nil? %>
          <p class="ml-2">
            <%= "--" %>
          </p>
        <% else %>
          <p class="ml-2">
            <%= (userbody.weight.to_f / (userbody.height.to_f / 100) ** 2).round(1) %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="mt-1">
      <div class="userbody_title">想定基礎代謝</div>
      <% if [userbody&.height, userbody&.weight, userbody&.birth_year].include?(nil) %>
        <p class="ml-2">
          <%= '--kcal' %>
        </p>
      <% else %>
        <p class="ml-2">
          <%= "#{(66.47 + (13.75 * userbody.weight.to_f) + (5 * userbody.height.to_f) - (6.78*(2019 - userbody.birth_year))).round(0)} kcal" %>
        </p>
      <% end %>
    </div>
    <div class="mt-1">
      <div class="userbody_title">筋トレ歴</div>
      <% if userbody&.experience.nil? %>
        <p class="ml-2">
          <%= '--' %>
        </p>
      <% else %>
        <p class="ml-2">
          <%= "#{((Date.today.year - userbody.experience.year)*12 + Date.today.month - userbody.experience.month) / 12 + 1} 年目" %>
        </p>
      <% end %>
    </div>
    <hr/>
  </div>
</div>