config/routes.rb
Rails.application.routes.draw do
  get 'todo_lists/index'
  get 'todo_items/index'
  get 'columns/index'
  get 'toppages/index'
  get 'images/index'
  get 'users/index'
  get 'training_records/index'

  devise_for :users
  root to:"toppages#index"

  resources :toppages, only: :index do
    collection do
      get 'privacy_policy'
      get 'regulation'
      get 'contact_us'
      get 'administrator_info'
    end
  end

  resources :columns do
  end

  resources :todo_lists do
    resources :todo_items
  end

  resources :users, only: [:index, :show] do
    member do      #id含む
      get 'records_update'
    end
    collection do  #id含まない
      get 'pagination'
    end
    resources :images, except: [:new, :show]
    resources :user_bodies, only: [:new, :create, :update]
    resources :training_records, only: [:index, :create, :destroy] do
      collection do
        get :draw_graph
      end
    end
  end

  resources :exercises, only: :index do
  end

  resources :relationships, only: [:create, :destroy] do
  end
end

app/models/column.rb
class Column < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :part

  belongs_to :user
  has_one_attached :image

  #ジャンルの選択が「--」の時は保存できないようにする
  validates :category_id,:part_id, numericality: { other_than: 0}
  
  with_options presence: true do
    validates :name
    validates :introduction
    validates :category_id
    validates :part_id
  end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @columns = Column.all.order("created_at DESC")
  end

  def new
    @column = Column.new
  end

  def create
    @column = Column.new(column_params)
   if @column.save
      redirect_to columns_index_path
    else
     render :new
   end
  end

  def show
  end

  def edit
  end

  def update
    if @column.update(column_params)
      redirect_to column_path
    else
      render :edit
    end
  end

  def destroy
    @column.destroy
    redirect_to root_path
  end

  private
  def column_params
    params.require(:column).permit(:name, :introduction, :category_id, :part_id, :image).merge(user_id: current_user.id)
  end

  def set_item
    @column = Column.find(params[:id])
  end

  def move_to_index
    unless @column.user.id == current_user.id
      redirect_to action: :index
    end
  end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/columns/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>
<%= render "shared/header" %>
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('show.edit.logo.png' , size: '185x60'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">情報を入力</h2>
    <%= form_with(model: @column, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        トップ画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"タイトル（※200文字まで入力できます)", maxlength:"200" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          詳細
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info", placeholder:"【例】結論（何を伝えたいのか）、理由（なぜそう言えるのか）、根拠（理由を裏付けるデータ）、参考文献(動画や論文、ニュースのURL）" ,rows:"50" ,maxlength:"1000000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">分類</div>
      <div class="form">
        <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          トレーニングの部位
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:part_id, Part.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する", class:"sell-btn" %>
      <%=link_to 'もどる', column_path, method: :get, class:"back-btn" %>
    </div>

  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/columns/index.html.erb
<%= render "shared/header" %>

  <div class='item-contents'>
    <h2 class='title'>最近の情報</h2>
    <div class="subtitle" >
      <p>トレーニング・食事・サプリメント等、必要な情報は全てここから</p>
    </div>
    <ul class='item-lists'>

      <%  if @columns.present? %>
        <% @columns.each do |column| %>
          <li class='list'>
            <%= link_to column_path (column.id) do %>
            <div class='item-img-content' >
              <%= image_tag column.image, class: "item-img" %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= column.name %>
              </h3>
            </div>
            <div class='item-price'>
              <span><%= column.category.name %></span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'></span>
              </div>
            </div>
          </div>
        <% end %>
          </li>
        <% end %>
      <% else %>
        <li class='list'>
          <%= link_to columns_index_path do %>
          <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              体づくりの情報を投稿してね
            </h3>
          </div>
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to(new_column_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'push.logo.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/columns/new.html.erb
<%= render "shared/header" %>
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('show.edit.logo.png' , size: '185x60'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">情報を入力</h2>
    <%= form_with model:@column, local: true do |f| %>
     <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        トップ画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"タイトル（必須 200文字まで)", maxlength:"200" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          詳細
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info", placeholder:"【例】結論（何を伝えたいのか）、理由（なぜそう言えるのか）、根拠（理由を裏付けるデータ）、参考文献(動画や論文、ニュースのURL）" ,rows:"50" ,maxlength:"1000000" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text">分類</div>
      <div class="form">
        <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          トレーニングの部位
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:part_id, Part.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/columns/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
       <%= @column.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @column.image ,class:"item-box-img" %>
    </div>

    <% if user_signed_in? %> 
      <% if current_user.id == @column.user_id %>
        <%= link_to "編集", edit_column_path, method: :get, class: "item-red-btn" %>
          <p class="or-text">or</p>
        <%= link_to "削除", "/columns/#{@column.id}", method: :delete, class:"item-destroy" %>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @column.introduction %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @column.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">ジャンル</th>
          <td class="detail-value"><%= @column.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">トレーニングの部位</th>
          <td class="detail-value"><%= @column.part.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @column.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>